### ISSUE TITLE
本地docker部署无法联网，202 Ratelimit

### ISSUE THREAD

**Issue by hfoi589** [binjie09/duckduckgo-api#23]
访问端口网页提示The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

查看后台日志:
2024-05-08T23:46:20.429958317Z /usr/local/lib/python3.9/asyncio/events.py:80: UserWarning: lxml is not installed. Using backend='api'.
2024-05-08T23:46:20.429996425Z   self._context.run(self._callback, *self._args)
2024-05-08T23:46:21.483796001Z [2024-05-09 07:46:21,469] ERROR in app: Exception on /search [GET]
2024-05-08T23:46:21.483831605Z Traceback (most recent call last):
2024-05-08T23:46:21.483856771Z   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
2024-05-08T23:46:21.483862445Z     response = self.full_dispatch_request()
2024-05-08T23:46:21.483866737Z   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
2024-05-08T23:46:21.483871288Z     rv = self.handle_user_exception(e)
2024-05-08T23:46:21.483875185Z   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
2024-05-08T23:46:21.483879346Z     rv = self.dispatch_request()
2024-05-08T23:46:21.483883409Z   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
2024-05-08T23:46:21.483887567Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-05-08T23:46:21.483891649Z   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 254, in __call__
2024-05-08T23:46:21.483895803Z     return call_result.result()
2024-05-08T23:46:21.483899705Z   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
2024-05-08T23:46:21.483903910Z     return self.__get_result()
2024-05-08T23:46:21.483908091Z   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
2024-05-08T23:46:21.483912153Z     raise self._exception
2024-05-08T23:46:21.483916191Z   File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 331, in main_wrap
2024-05-08T23:46:21.483920180Z     result = await self.awaitable(*args, **kwargs)
2024-05-08T23:46:21.483924263Z   File "/app/app.py", line 26, in search
2024-05-08T23:46:21.483928195Z     ddgs_gen = ddgs.text(keywords, safesearch='Off', timelimit='y', backend="lite")
2024-05-08T23:46:21.483932447Z   File "/usr/local/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search.py", line 57, in text
2024-05-08T23:46:21.483936543Z     return self._run_async_in_thread(super().text(*args, **kwargs))
2024-05-08T23:46:21.483940867Z   File "/usr/local/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search.py", line 53, in _run_async_in_thread
2024-05-08T23:46:21.483945337Z     result = future.result()
2024-05-08T23:46:21.483950253Z   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
2024-05-08T23:46:21.483955149Z     return self.__get_result()
2024-05-08T23:46:21.483959936Z   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
2024-05-08T23:46:21.483964933Z     raise self._exception
2024-05-08T23:46:21.483969531Z   File "/usr/local/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 167, in text
2024-05-08T23:46:21.483974499Z     results = await self._text_api(keywords, region, safesearch, timelimit, max_results)
2024-05-08T23:46:21.483979735Z   File "/usr/local/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 258, in _text_api
2024-05-08T23:46:21.483991298Z     raise e
2024-05-08T23:46:21.483996071Z   File "/usr/local/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 253, in _text_api
2024-05-08T23:46:21.484000578Z     await asyncio.gather(*tasks)
2024-05-08T23:46:21.484004828Z   File "/usr/local/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 229, in _text_api_page
2024-05-08T23:46:21.484009181Z     resp_content = await self._aget_url("GET", "https://links.duckduckgo.com/d.js", params=payload)
2024-05-08T23:46:21.484013688Z   File "/usr/local/lib/python3.9/site-packages/duckduckgo_search/duckduckgo_search_async.py", line 124, in _aget_url
2024-05-08T23:46:21.484018149Z     raise RatelimitException(f"{resp.url} {resp.status_code} Ratelimit")
2024-05-08T23:46:21.484022685Z duckduckgo_search.exceptions.RatelimitException: https://links.duckduckgo.com/d.js?q=hi&kl=wt-wt&l=wt-wt&p=&s=0&df=y&vqd=4-185712780087836999332350966763191802734&ex=-2 202 Ratelimit

**Comment by hfoi589** [comment]
emmm。。。。好像是因为没翻上墙，surge里duckduckgo.com调为代理模式，就连上了

**Comment by axdlee** [comment]
升级一下requirement里duckduckgo_search的版本就好了，duckduckgo-search>=6.1.0。
然后自己打个docker镜像，或者用我的 xdlee/duckduckgo-api:latest
