### ISSUE TITLE
报错：500

### ISSUE THREAD

**Issue by zeraturing** [binjie09/duckduckgo-api#4]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app.py", line 12, in hello_world
    max_results = int(request.args.get('max_results')) or 3
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by zeraturing** [comment]
[2023-05-10 05:53:10,149] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'search' did not return a valid response. The function either returned None or ended without a return statement.
